### ISSUE TITLE
Review precaster's details at south wall beam

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#101]
Details:
CTR\_closed_cannery district - eau claire\Building Products\03 - Concrete\03 40 00 Precast Concrete\20191126 - from Precast Eng - Details at Precast Beam - for review

from precast supplier

> Here is the connection design for the exterior LB beam along grid 6 at the knock-out cmu wall. Please review and comment if needed.

> Take note of the top of CIP pier elevation and the cip blockout to accommodate beam height and beam bearing distances.

> Also note the required 1” gap joint from beam end to cip wall edge. All this maintains the 24’-0” clear i.s. to i.s. at the temporary cmu wall opening.

**Comment by theoryshaw** [comment]
@lcpt i'll take an initial stab at reviewing.

**Comment by theoryshaw** [comment]
@lcpt 

Here's my review...
CTR\_closed_cannery district - eau claire\Building Products\03 - Concrete\03 40 00 Precast Concrete\20191127 - from ARCH to STRUCT - reviewed precast beam details\20191127 - precast beam at south wall - OD reviewed.pdf

If you can, please take a quick review as well. 

Thanks, Ryan

**Comment by lcpt** [comment]
OK. I'll do it now.

**Comment by lcpt** [comment]
Here's mine:

_CLOSED_Cannery District - Eau Claire/Building Products/03 - Concrete/03 40 00 Precast Concrete/20191127 - from STRUCT to ARCH - reviewed precast beam details
