### ISSUE TITLE
1st floor wall at the south of the ramp

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#102]
@lcpt Possible to sketch up the condition below?

The precast supplier was asking.

![image](https://user-images.githubusercontent.com/507113/69661667-6e279900-1048-11ea-8f34-ce1f64a6a132.png)

**Comment by lcpt** [comment]
![1st_floor_wall_south_ramp_connections](https://user-images.githubusercontent.com/12873038/69741176-dfe00f80-113a-11ea-9a9f-dc3c390ec5ee.jpeg)
I think this can work.

**Comment by theoryshaw** [comment]
Thanks Luis, do we need starter rebar drilled into the plank, that would extend up into the RC wall?

**Comment by lcpt** [comment]
The wall doesn't need to bear into the precast floor which, in turn is not intended to support the wall. If we join them we don't master the way they work. I think it's better to let them "mechanically" apart.

**Comment by theoryshaw** [comment]
i gotcha, so that RC wall is a big beam essentially.

**Comment by theoryshaw** [comment]
I have a feeling, however, they might want to use CMU at this condition.

**Comment by lcpt** [comment]
Yeah, it's a big beam which help us resist horizontal forces coming from 1st floor too. I feel very comfortable having this RC wall there :). Specially after all the discussions about the topping and the diaphragm forces with Reigstad.

**Comment by theoryshaw** [comment]
Sounds good. We'll push for that then. Thanks!
