### ISSUE TITLE
(non-bearing) party walls between the units go with 2x6's 24" o.c.?

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#115]
Hi @lcpt,

At the (non-bearing) party walls between the units, the GC was wondering if they could go with 2x6's at 24" o.c.

Okay?

Thanks, Ryan
![Revu_Do96etqDcR](https://user-images.githubusercontent.com/507113/70826729-46a53000-1dad-11ea-9445-e81d06a4c5b3.png)

**Comment by lcpt** [comment]
OK for those that are not shear walls:
![1st_floor_key_plan](https://user-images.githubusercontent.com/12873038/70903815-05588e80-2000-11ea-8ab5-a8a7c191a0a8.png)
![2nd_floor_key_plan](https://user-images.githubusercontent.com/12873038/70903817-05f12500-2000-11ea-82cf-64778785a093.png)
![3rd_floor_key_plan](https://user-images.githubusercontent.com/12873038/70903818-05f12500-2000-11ea-9386-b628ea8a83ab.png)
