### ISSUE TITLE
Stud spacement in shear walls S2A and S2B

### ISSUE THREAD

**Issue by lcpt** [OpeningDesign/CTR#116]
![2nd_floor_key_plan](https://user-images.githubusercontent.com/12873038/70905934-7484b180-2005-11ea-80ac-4d8f4e82aaf3.png)
There is an error in the bearing wall schedule for those walls in the second floor. The spacing there must be 12 inches (ca. 30 cm):

![image](https://user-images.githubusercontent.com/12873038/70906077-d6ddb200-2005-11ea-9f77-22457ae54a08.png)

**Comment by theoryshaw** [comment]
sounds good.  Will update plans.
