### ISSUE TITLE
(2) 2x12's rim boards for the floor trusses

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#117]
@lcpt 

Instead of LVL rim boards for the floor trusses, the GC would like to use (2) 2x12's instead. 

Would this be okay?

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/71186321-4dd0b000-227d-11ea-89d0-f543179651f0.png)

As you can see it's not a standard design. I think it's not a good idea.

**Comment by theoryshaw** [comment]
...as you would expect from a institution for engineered wood, would say. ;)

**Comment by lcpt** [comment]
Yeah, it's not always a good idea to ask your hairdresser if you need a hair cut. But it's also true that the shear stress can't go through the joint between the panels. You can always make a calculation like the one we did for the corridor joists to see what happens but this takes time...
