### ISSUE TITLE
Review elevator shops

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#118]

**Comment by theoryshaw** [comment]
@lcpt Can you review these as well?

CTR\_closed\Products\14 - Conveying Equipment\Elevators\KONE\Submittals\20191114\KONE Approval Submittal 2019-11-13 Cannery Trails.pdf

**Comment by theoryshaw** [comment]
fyi, Kone confirmed that we can change the hoistway width to 7'-0"
![image](https://user-images.githubusercontent.com/507113/71604885-8e0c1a00-2b2a-11ea-9734-42b2555a831a.png)

**Comment by theoryshaw** [comment]
@lcpt 

FYI, here's our review so far...
CTR\\_closed\Products\14 - Conveying Equipment\Elevators\KONE\Submittals\20191114\20191231 - KONE Approval Submittal 2019-11-13 Cannery Trails - OD Reviewed.pdf

**Comment by lcpt** [comment]
I've reviewed those plans and, apart the question about the openings we have chatted about, I have no remarks about them.
