### ISSUE TITLE
Changes in 2bd

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#130]
Master Bath in 2BD
- change tub to shower
- remove door from hallway to master bath
- remove small linen closets (convert this space to an alcove next to the unit's entry)

Smaller Bath in 2BD
- change shower to tub
- add door from hallway to bath
- remove small linen closets

**Comment by bdmock** [comment]
![image](https://user-images.githubusercontent.com/3970626/71759406-31826500-2e72-11ea-83a5-046d9b6bbb66.png)
![image](https://user-images.githubusercontent.com/3970626/71759434-9f2e9100-2e72-11ea-9fca-9ff84a36331d.png)
(pg 9 https://www.bozeman.net/Home/ShowDocument?id=60)

**Comment by bdmock** [comment]
The bozeman document shows this as the only option for showers in the Type A bathrooms

**Comment by bdmock** [comment]
![image](https://user-images.githubusercontent.com/3970626/71759483-3a276b00-2e73-11ea-9a76-3b7e6fa5a1ab.png)

This seems the way to go. Am I right in thinking so?

**Comment by bdmock** [comment]
at least in the Type A 2bd master bath

**Comment by theoryshaw** [comment]
I think we can get away with this...

![image](https://user-images.githubusercontent.com/507113/71759965-b625b100-2e7b-11ea-8f28-23a094d086e6.png)

---

1.  
![image](https://user-images.githubusercontent.com/507113/71759979-da818d80-2e7b-11ea-8e8b-44ac52bcd2d1.png)

![image](https://user-images.githubusercontent.com/507113/71759998-35b38000-2e7c-11ea-8ba9-92a4a375f3f7.png)

![image](https://user-images.githubusercontent.com/507113/71760012-6bf0ff80-2e7c-11ea-9893-4e5a484d27f7.png)

**Comment by bdmock** [comment]
http://dev.first-draft.xyz/d/20191230_CTR_Unit_Revisions/

**Comment by bdmock** [comment]
![image](https://user-images.githubusercontent.com/3970626/71771430-43124e00-2f00-11ea-9cce-43d6ec237701.png)
The smaller bath doesn't really allow for a forward door approach to the hallway door.

**Comment by bdmock** [comment]
http://dev.first-draft.xyz/d/20200104_CTR_Unit_Revisions/
