### ISSUE TITLE
Relocate washer/dryer

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#131]
![image](https://user-images.githubusercontent.com/507113/71264806-7b176f80-230a-11ea-90cb-e3e4435dfab8.png)

https://www.dropbox.com/s/cnkkv1c6n295w4p/bxKC83saIB.mp4?dl=0

Do this for all the STs on all the floors

**Comment by bdmock** [comment]
![image](https://user-images.githubusercontent.com/3970626/71281208-ec631c80-2322-11ea-9341-00b31cc452eb.png)
![image](https://user-images.githubusercontent.com/3970626/71281233-00a71980-2323-11ea-8146-d5d0cef0771d.png)
Can you catch the view template adjustment? It's not supported in LT.

**Comment by theoryshaw** [comment]
![image](https://user-images.githubusercontent.com/507113/71281456-8fb43180-2323-11ea-8efa-b3b1c1d94ace.png)
 
haha
