### ISSUE TITLE
Reconfigure 1BD

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#132]
> Make a large walk-in closet and relocate laundry (get rid of small door next to laundry). If you need to make the living room a little smaller for clearance, then go ahead and do it and move the wall.

Maybe something like this...

![Revu_vu1NdXPZeD](https://user-images.githubusercontent.com/507113/71268652-07c62b80-2313-11ea-94c7-211676760b6a.png)

**Comment by bdmock** [comment]
http://dev.first-draft.xyz/d/20191230_CTR_Unit_Revisions/
(sketch to be updated w/ 2bd push)
