### ISSUE TITLE
 hold down detail at shear wall at Grid 1, 0-A.1

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#134]
hold down detail at shear wall at Grid 1, 0-A.1

**Comment by lcpt** [comment]
![20191230_084809](https://user-images.githubusercontent.com/12873038/71664680-26d4ac80-2d5a-11ea-8bdb-341b48200580.jpg)
This is the sketch sent by Grant. The wall is already poured, isn't it?

**Comment by theoryshaw** [comment]
Yes it is poured.

**Comment by lcpt** [comment]
![connection_sketch](https://user-images.githubusercontent.com/12873038/72181583-f7711000-33e9-11ea-9d02-596765710211.jpeg)

**Comment by theoryshaw** [comment]
seems good to me. Were you planning on forwarding this to Grant?

**Comment by lcpt** [comment]
I sent it Friday evening.
