### ISSUE TITLE
update the plans relative to speced washer/dryer

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#137]
heres' the specs..
CTR/_closed/Products/22 - Plumbing/224000 - Plumbing Fixtures/Stacked Washer Specs.pdf

![image](https://user-images.githubusercontent.com/507113/71759457-e026a580-2e72-11ea-8bd7-f4180ebb7946.png)

**Comment by theoryshaw** [comment]
you need to create a new door type too.  

![image](https://user-images.githubusercontent.com/507113/71759559-7a3b1d80-2e74-11ea-94ee-be32e8921795.png)

These offset pivot doors probably won't make the budget, but let's propose this for now.

**Comment by bdmock** [comment]
ok

**Comment by theoryshaw** [comment]
Probably makes sense if that's a 2x6 wall.
![image](https://user-images.githubusercontent.com/507113/71761097-bf6b4980-2e8c-11ea-9eae-6a665b860833.png)

**Comment by bdmock** [comment]
Swept through all units
