### ISSUE TITLE
Issues with flush steel beams over store front areas (9 on S214), etc..

### ISSUE THREAD

**Issue by lcpt** [OpeningDesign/CTR#140]
![image](https://user-images.githubusercontent.com/12873038/72263945-2b327c80-361a-11ea-9ed7-013070c489d3.png)

They want to replace the steel beam by a set of LVL header adding two supports.
The problem with this is that those supports introduce loads that have not been considered for the precast floor design.

I've not seen any explanation about the problem with our "splitted" steel beam. I'll ask Kurt about it.

**Comment by theoryshaw** [comment]
The screenshoot you show here was a proposed layout by Kurt awhile ago.  I decided not to entertain it, because exactly as you proposed--that is, the loads were different than what the precaster was giving originally. And it was too late in the game to change them.

**Comment by theoryshaw** [comment]
I will forward you the email where this decision was made.  I think you were cc'ed on it.

**Comment by theoryshaw** [comment]
related to #142

**Comment by lcpt** [comment]
Yes I've received that mail.
Thank you.

**Comment by theoryshaw** [comment]
closing - #142 is duplicate
