### ISSUE TITLE
Detail 6 on S215: height of the double plate.

### ISSUE THREAD

**Issue by lcpt** [OpeningDesign/CTR#141]
![image](https://user-images.githubusercontent.com/12873038/72266170-1c4dc900-361e-11ea-9381-45e452fdd3c3.png)

Jeff Holm: "_detail 6 on S215 will need to be clarified as well, I do not see an actual height of the double top plate on the partially flush beam._"

**Comment by lcpt** [comment]
This double plate is simply the double plate that runs over all the wall studs. Am I missing something?

**Comment by theoryshaw** [comment]
I'm not sure either.

If we can, however, I think we should do something like this instead.

![image](https://user-images.githubusercontent.com/507113/72389959-37d4d480-36ef-11ea-9df4-220aae7259a1.png)  That is, instead of 'tucking' the header up into the truss. 

Thanks, Ryan

**Comment by lcpt** [comment]
OK, I agree.
