### ISSUE TITLE
Design W-section under 2nd floor trusses at the following locations...

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#142]
Design W-section under 2nd floor trusses at the following locations...

![image](https://user-images.githubusercontent.com/507113/72389638-75852d80-36ee-11ea-9121-e71037961df1.png)

**Comment by lcpt** [comment]
We can use a W16X57 for both beams.

**Comment by theoryshaw** [comment]
Thanks Luis, possible to use a thicker W12 here?

We could use the head room, if possible.

**Comment by theoryshaw** [comment]
Or a W14, if that's not possible.

**Comment by lcpt** [comment]
> Thanks Luis, possible to use a thicker W12 here?
> 
> We could use the head room, if possible.

Yes W12X87. In both cases (W12 or W16) the beams must be continuously braced. I would like to check the modified drawings.

**Comment by theoryshaw** [comment]
Thanks, yes, I plan having you review the entire set in the next couple days.

Can you provide a sketch on what you mean by this cont. bracing?

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/72685215-49035400-3ae8-11ea-92dc-61b3aba53ae1.png)
The horizontal displacement of the upper flange must be constrained as in the picture (for example) to prevent lateral buckling.

**Comment by theoryshaw** [comment]
I guess i'm still not following. 

With the W12x87 we have this conditon, so far... (disregard the garage door spring)

![image](https://user-images.githubusercontent.com/507113/72685353-f5284900-3aae-11ea-9ca5-f3110fe68404.png)

**Comment by lcpt** [comment]
Ah, OK. They go under the trusses. We need to attach the upper flange of the steel beam to the lower chord of the trusses. I'll seek for a suitable detail. 
![w_section_under_trusses png](https://user-images.githubusercontent.com/12873038/72685461-92ed3980-3aea-11ea-8031-cf6b33ea5e8e.png)

**Comment by theoryshaw** [comment]
sounds good

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
We could use this kind of connectors:
![20200122100117_001](https://user-images.githubusercontent.com/12873329/72884836-16837200-3d07-11ea-9321-3429673f81a6.jpg)
![simpson_strong_tie](https://user-images.githubusercontent.com/12873329/72884872-269b5180-3d07-11ea-9e52-d91325f51c69.gif)
![table](https://user-images.githubusercontent.com/12873329/72884895-31ee7d00-3d07-11ea-9169-4bea80e245b8.gif)
http://advancedstructuralconnectors.com/product/ccqeccq-column-caps/

**Comment by theoryshaw** [comment]
Below is how it's typically done, where a wood 2x sill is attached to the beam, and then the truss is attached to the sill. 

Welding is too cumbersome and expensive. 

![image](https://user-images.githubusercontent.com/507113/72937219-56118480-3d2e-11ea-9214-cb7ab42a502b.png)

**Comment by theoryshaw** [comment]
![image](https://user-images.githubusercontent.com/507113/72959392-cab8e300-3d6f-11ea-8c6d-cc7d98a844a2.png)

**Comment by anaiortega** [comment]
Yes, the idea of that solution with steel connectors was to minimize the total beam height so as not to take up more head room.

**Comment by anaiortega** [comment]
![pic](https://user-images.githubusercontent.com/12873329/72974573-83623f00-3dcf-11ea-9773-aa07249135fa.png)
