### ISSUE TITLE
LVL near ramp on 2nd floor

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#144]
@lcpt 

This following beam circled below, seems undersized.  Can you verify?

Thanks, Ryan
![image](https://user-images.githubusercontent.com/507113/72676325-b1edbc00-3a55-11ea-884a-e66b4ca28ac8.png)

**Comment by theoryshaw** [comment]
This one seems undersized too, as it's bearing the 3rd and rooftop trusses through the 2nd and 3rd floor corridor walls.

![image](https://user-images.githubusercontent.com/507113/72762034-bf18c100-3ba3-11ea-9bce-bb29d833fc22.png)

![image](https://user-images.githubusercontent.com/507113/72762358-e9b74980-3ba4-11ea-878c-8d995279fa0c.png)

**Comment by lcpt** [comment]
> @lcpt
> 
> This following beam circled below, seems undersized. Can you verify?
> 
> Thanks, Ryan
> ![image](https://user-images.githubusercontent.com/507113/72676325-b1edbc00-3a55-11ea-884a-e66b4ca28ac8.png)

There is a door over this header on the 3rd floor but I agree that it's better to make it more robust: 5.25×14"

**Comment by lcpt** [comment]
> This one seems undersized too, as it's bearing the 3rd and rooftop trusses through the 2nd and 3rd floor corridor walls.
> 
> ![image](https://user-images.githubusercontent.com/507113/72762034-bf18c100-3ba3-11ea-9bce-bb29d833fc22.png)
> 
> ![image](https://user-images.githubusercontent.com/507113/72762358-e9b74980-3ba4-11ea-878c-8d995279fa0c.png)

Yes it was undersized. We can use also a  5.25×14" LVL header.
