### ISSUE TITLE
(2) sistered 4x6's at headers in the corridor

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#145]
@lcpt 

For the following conditions in the project, can be go with (2) sistered 4x6's instead?

![image](https://user-images.githubusercontent.com/507113/72676366-1e68bb00-3a56-11ea-8d0b-9e893def5da6.png)

**Comment by lcpt** [comment]
> @lcpt
> 
> For the following conditions in the project, can be go with (2) sistered 4x6's instead?
> 
> ![image](https://user-images.githubusercontent.com/507113/72676366-1e68bb00-3a56-11ea-8d0b-9e893def5da6.png)

Yes, we can.
