### ISSUE TITLE
wood bearing wall along ramp walls

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#146]
@lcpt, 

I would like to have this furring, that bears the 2nd floor trusses be 2x4's. 

What's you recommended on center spacing? 16"?

![image](https://user-images.githubusercontent.com/507113/72676733-16ab1580-3a5a-11ea-856a-0c66856f21cb.png)

**Comment by lcpt** [comment]
You can use a spacing of 24" and double them (2) 2×4 at 24 inches (0.61 m) and place them under the trusses or use single studs at 12 inches (0.3 m).
