### ISSUE TITLE
Modify corridor floors assembly composition.

### ISSUE THREAD

**Issue by lcpt** [OpeningDesign/CTR#147]
[20200117_0444_Ryan2Luis_corridor_floors.pdf](https://github.com/OpeningDesign/CTR/files/4083220/20200117_0444_Ryan2Luis_corridor_floors.pdf)

**Comment by lcpt** [comment]
We can use 4x6 pine joists as follows:
![4x6_pine_joist_imperial_units](https://user-images.githubusercontent.com/12873038/72747519-28ed9680-3bb5-11ea-9201-84adcdfbe82c.png)

**Comment by theoryshaw** [comment]
Cool. Thx!  Are you still working on the substrate layer sandwich?

![image](https://user-images.githubusercontent.com/507113/72749573-0d1bcd80-3b80-11ea-9436-6c03329a4a39.png)

**Comment by lcpt** [comment]
> Cool. Thx! Are you still working on the substrate layer sandwich?
> 
> ![image](https://user-images.githubusercontent.com/507113/72749573-0d1bcd80-3b80-11ea-9436-6c03329a4a39.png)

Yes. For the structural point of view I prefer the first sandwich. But, on the other hand, I need to check the strength of the OSB panels. I'm currently working on this.

**Comment by lcpt** [comment]
> Cool. Thx! Are you still working on the substrate layer sandwich?
> 
> ![image](https://user-images.githubusercontent.com/507113/72749573-0d1bcd80-3b80-11ea-9436-6c03329a4a39.png)

Hi Ryan. In those sandwiches there is a missing OSB layer. We checked the floor sheathing with three 19/32 structural plywood layers:
![image](https://user-images.githubusercontent.com/12873038/72799501-a660e780-3c45-11ea-9259-5c657fa09efc.png)

**Comment by theoryshaw** [comment]
Thats the question, essentially, can we go down to 2 layers? Perhaps (2) 3/4" layers? The gyp crete provides some fire resistant in these sandwiches, as well.

**Comment by lcpt** [comment]
OK. Understood.

**Comment by lcpt** [comment]
Then we need to put the Gypcrete between the two structural layers, otherwise there is no bearing layer in case of fire.

**Comment by theoryshaw** [comment]
Sounds good.  If we do the following what's the minimum size of the OSB?

![image](https://user-images.githubusercontent.com/507113/72812119-8968ec00-3c26-11ea-966f-38a914a59be6.png)

**Comment by lcpt** [comment]
We can use a 19/32 OSB panel with the following design capacities:

![image](https://user-images.githubusercontent.com/12873038/72829244-b3e69380-3c7e-11ea-833a-4cdc744bfeb3.png)

![image](https://user-images.githubusercontent.com/12873038/72829343-e1334180-3c7e-11ea-850f-76d39a880ddd.png)

**Comment by theoryshaw** [comment]
Okay.  so to summarize... 

We can do?...

4x6 no. 1 pine joists 32" o.c. with the following sandwich...
- 19/32" osb spanning 32" oc.
- 3/4" gyp crete
- acoustical mat
- 19/32" osb spanning 32" oc.

**Comment by lcpt** [comment]
Yes, as long as the OSB panels have the capacities showed above.

**Comment by theoryshaw** [comment]
@lcpt,

In our previous assembly, we had the following sandwich....

- 3/4" gyp crete
- acoustical mat
- 19/32" osb spanning 32" oc.
- 19/32" osb spanning 32" oc.
- 19/32" osb spanning 32" oc.

Is there anyway to go down to 2 layers like the following?...

- 3/4" gyp crete
- acoustical mat
- 3/4" (or thicker, if need be) osb spanning 32" oc.
- 3/4" (or thicker, if need be)  osb spanning 32" oc.

Sorry to ask this again, but the GC has expressed concerns on the constructability of the following sandwich

- 19/32" osb spanning 32" oc.
- 3/4" gyp crete
- acoustical mat
- 3/4" osb spanning 32" oc.

With this assembly, they would put that first layer of 3/4" down, and that would be the only sheathing during construction.  They are worried about large concentrated loads during construction, such as a cart full of drywall. 

They also indicated that that top layer of 19/32" would be hard to nail down through the gyp. crete. 

---

It would be ideal to do the following sandwich...

- 3/4" gyp crete
- acoustical mat
- 3/4" (or thicker, if need be) osb spanning 32" oc.
- 3/4" (or thicker, if need be)  osb spanning 32" oc.

..but if it's not possible to us (2) layers of OSB, I think we should just go back the following then.

- 3/4" gyp crete
- acoustical mat
- 19/32" osb spanning 32" oc.
- 19/32" osb spanning 32" oc.
- 19/32" osb spanning 32" oc.

**Comment by lcpt** [comment]
Hi Ryan.

You can use:

- 3/4" gyp crete
- acoustical mat
- 19/32" osb spanning 32" oc.
- 1 1/8" osb spanning 32" oc.

or go back to the initial solution:

- 3/4" gyp crete
- acoustical mat
- 19/32" osb spanning 32" oc.
- 19/32" osb spanning 32" oc.
- 19/32" osb spanning 32" oc.

**Comment by lcpt** [comment]
We need to adapt detail 4/A800 consequently.
