### ISSUE TITLE
Steel at precast cantilever

### ISSUE THREAD

**Issue by anaiortega** [OpeningDesign/CTR#149]
Eliminate stiffener plate and replace bolts with full weld

**Comment by anaiortega** [comment]
It's possible to eliminate the stiffener plates in the beam over the column, but only in the case that no other loads except the precast self-weight are  acting on the cantilever or the precast slab before the grout is in place.
![20200128150036_001](https://user-images.githubusercontent.com/12873329/73275849-0298ae00-41e8-11ea-9607-6ec377878da0.jpg)

**Comment by lcpt** [comment]
It's also possible to weld the plate to the bottom web of the beam. You can also reduce the plate dimensions to 9×9 inches to leave some space to the weld bead.
