### ISSUE TITLE
Callout the base/top plates for the remaining steel. 

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#150]
Callout the base/top plates for the remaining steel. 

http://dev.first-draft.xyz/d/20200212_2nd_Floor_Steel/

**Comment by theoryshaw** [comment]
I think we should sketch out the base plates, but I think we can just call out, with notes in a schedule, what the top plates (size, bolts, etc) are, as well as the the intersection of these steel next to the cantilever. 

(just trying to save us time having to model up every single detail.  We can lean on the structural shops to draft these connections up, and we can review)

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
Here is the sketch
![20200217113128_001](https://user-images.githubusercontent.com/12873329/74650783-b99e9e80-5182-11ea-96b6-b95d9b2a0150.jpg)

**Comment by theoryshaw** [comment]
Thanks Ana, were you planning to sketch out the base plate conditions called out here?

http://dev.first-draft.xyz/d/20200212_2nd_Floor_Steel/

**Comment by anaiortega** [comment]
Correction to previous sketch: all cap plates are 10x14x3/4
![20200217155735_001](https://user-images.githubusercontent.com/12873329/74669249-0f853d80-51a7-11ea-82e4-f2f9c634afa1.jpg)

**Comment by anaiortega** [comment]
I send the base plates in a few minutes

**Comment by anaiortega** [comment]
All base plates are:
![20200217164806_001](https://user-images.githubusercontent.com/12873329/74672964-97bb1100-51ae-11ea-94eb-91aba858448d.jpg)

**Comment by theoryshaw** [comment]
Can you coordinate your suggested base plate dimensions with the existing conditions of the curb and precast offset.  

![image](https://user-images.githubusercontent.com/507113/74674810-c8338880-5177-11ea-98e2-fd2159e3144d.png)

![image](https://user-images.githubusercontent.com/507113/74674826-d2558700-5177-11ea-8ee7-adbc359972df.png)

**Comment by anaiortega** [comment]
Base plates North façade
![20200219144312_001](https://user-images.githubusercontent.com/12873329/74845451-5605a400-532f-11ea-867a-c322e93c0f6d.jpg)

**Comment by anaiortega** [comment]
![20200219160059_001](https://user-images.githubusercontent.com/12873329/74850327-24460a80-533a-11ea-9735-aad02ce300d9.jpg)
![20200219160138_001](https://user-images.githubusercontent.com/12873329/74850331-2740fb00-533a-11ea-8887-d45d4a199d75.jpg)

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
Can this be a suitable alternative?
![20200220084405_001](https://user-images.githubusercontent.com/12873329/74916911-f6f36e00-53c6-11ea-9831-1f6b7fe08bd0.jpg)

**Comment by theoryshaw** [comment]
Yes, this works.  Thanks.

**Comment by lcpt** [comment]
The horizontal stirrup is missing here: 
![image](https://user-images.githubusercontent.com/12873038/75887011-6cc8f200-5e29-11ea-9305-266595a755dd.png)

**Comment by theoryshaw** [comment]
okay.
