### ISSUE TITLE
Studio transom

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#31]
Translucent transom in studio, where the gap would be on the top of the wall facing the outdoor windows from living room. This will help a little more light to get through to the bedroom but also aid in the privacy. Furthermore, see if we can add a sliding “barn” door to the entrance of the studio bedrooms.

**Comment by bdmock** [comment]
Is the transom the polycarbonate material?

**Comment by theoryshaw** [comment]
you could put that as a placeholder, yes

**Comment by theoryshaw** [comment]
you could make it a different 'type'.. so it's easy to swap, if and when it changes.
