### ISSUE TITLE
Research on Modular Stairs

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#33]
https://pacificstair.com/

**Comment by chopinregis** [comment]
- email Tracy (vp of sales) from Pacificstair.com at tracy@pacificstair.com

**Comment by chopinregis** [comment]
Scott Sullivan - Sales representative for WI
erectastep.com
843-359-8755
ssullivan@erectastep.com

--------------------------------
lapeyrestair.com
Ls.sales@LapeyreStair.com
504-733-6009

--------------------------------

**Comment by chopinregis** [comment]
www.ezaccess.com/commercial
installed as needed
ksoyring@ezaccess.com
Kim Soy Ring
800 258 8503 option 3
takes either today or later in morning for a quote.

**Comment by chopinregis** [comment]
Questions to ask about stairs to company rep
- commerical grade.. within a fire stair aka ehavy duty
- Are these stairs self supporting, or can they be supported off the CMU wall?
- Is there an ideal floor to floor dimensions?
- Are they welded or bolted?

**Comment by chopinregis** [comment]
got a call from 
Scott Sullivan - Sales representative for WI
erectastep.com
843-359-8755
ssullivan@erectastep.com

According to him his stairs are all modular, will be bolted, made of steel.
They do no provide anchoring specs, but if we need anchoring specs, he can get his engineers to design them for extra fees. 
He will get the quotes by monday as Friday is public holiday.
