### ISSUE TITLE
Magic-paks

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#34]
http://www.magic-pak.com/
CUSTOMER SUPPORT, TECHNICAL SUPPORT AND GENERAL INQUIRIES: 1-800-448-5872
ARCHITECT AND ENGINEER DESIGN SUPPORT: 1-866-282-7257

**Comment by theoryshaw** [comment]
@chopinregis Can you call Magic Pak and verify we can have a situation like this, where we're accessing the magik-pak from the closet.

Also, share the plans with them and try to get a sense what unit they would recommend. I think we're looking for an electric unit.

![image](https://user-images.githubusercontent.com/507113/57813241-086f6180-7735-11e9-9692-794243a84f87.png)

**Comment by chopinregis** [comment]
magic pak point of liason for inquiries concerning magic pack services in Wisconsin
monroe equipments - 262 783 8190
Ben Lane - Liason

Mr. Keith Smith -

**Comment by chopinregis** [comment]
david.hubbard@alliedair.com

had a phone chat, he basically said aslong as the Magic-Pak unit is located on the exterior wall and as long as there is enough room on the from to service it, so situation with Magic Pak Accessible from closet door is fine. 

sent email with plans, he will review them and call me to discuss the details.

**Comment by chopinregis** [comment]
Magic pak direct Liason - David Hubbard (866 282 7257)

Called back and basically said that according to him all seems well, we only have to make sure that the doors are a minimum of 30inch wide doors.
