### ISSUE TITLE
Comcheck

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#52]
![image](https://user-images.githubusercontent.com/507113/63894214-b257be80-c9b1-11e9-8c80-e5870e2f67f6.png)

![image](https://user-images.githubusercontent.com/507113/63894226-baaff980-c9b1-11e9-9832-91b6fcaa1df9.png)

**Comment by yorikvanhavre** [comment]
Info regarding point 2:

**SPS 363.0407 Total building performance.** **(1)** MANDATORY REQUIREMENTS.  This is a department exceptionto the requirements in IECC section C407.2: The requirements inIECC  section  C403.2.7  are  not  required  to  be  demonstrated  asmeans of compliance with this section. **(2)** TOTAL ENERGY PERFORMANCE.  This is a department infor-mational note to be used under IECC section C407:  Note:  Use ofIECC section C407 requires the total building energy cost to beequal  to  or  less  than  the  standard  reference  design  building,  asrequired under IECC section C401.2 item 3.  The 2015 IECC orASHRAE 90.1−2013 options shall be selected. **(3)** COMCHECK.  This is a department informational note to beused under IECC section C407:  Note:  COMcheck is a computerprogram that may be used only for determining building envelopeor lighting compliance.  The COMcheck computer program maybe downloaded at:http:/www.energycodes.gov/.  The most recentversion of COMcheck shall be used to demonstrate code compli-ance.  The  2015  IECC  or  ASHRAE  90.1−2013  options  shall  beselected.

https://docs.legis.wisconsin.gov/code/admin_code/sps/safety_and_buildings_and_environment/361_366/363.pdf

**Comment by theoryshaw** [comment]
And link..
https://docs.legis.wisconsin.gov/code/admin_code/sps/safety_and_buildings_and_environment/361_366/363/II/0407

**Comment by yorikvanhavre** [comment]
RESCheck done and passing with 1.1%.

Left to be done:

* Change R-value of courtyard floor from 35MIN to 63 AVERAGE in shell.rvt (Just in case it is not done yet)
* Point 2 above: _Please provide a report for the 2015 IECC per SPS 363.0407(3)_ Unclear to me what exactly needs to be done here, but I suppose by providing a RESCheck report we are complying...
* Point 3 above: Add Ryan's signature and seal to the report

All other items above are satisfied.
