### ISSUE TITLE
handrails on both sides

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#62]
![image](https://user-images.githubusercontent.com/507113/63894832-47a78280-c9b3-11e9-9419-99b0bfb1842e.png)

**Comment by yorikvanhavre** [comment]
Note - stairs are there everywhere in the model, on both sides, only there is one not appearing on 3rd floor plan view on sheets A460, A461, A462

**Comment by theoryshaw** [comment]
Yeah, maybe that was it. Not sure.

**Comment by yorikvanhavre** [comment]
Got it. Third floor plan bottom limit needed to be set to unlimited
