### ISSUE TITLE
Type A - A471 - maneuvering clearance

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#68]
![image](https://user-images.githubusercontent.com/507113/63895513-f3050700-c9b4-11e9-88ea-22fd66a80db5.png)

**Comment by bdmock** [comment]
Caused the creation of a new door type (3' width) with tag U18
![Capture](https://user-images.githubusercontent.com/3970626/64373960-67a8f880-cfe8-11e9-87a4-d731ae1ea5cd.JPG)

**Comment by theoryshaw** [comment]
no need to change the door. They mean this...
![image](https://user-images.githubusercontent.com/507113/64374264-0fbec180-cfe9-11e9-80af-4d9272f03e0b.png)

**Comment by bdmock** [comment]
Then the unit doesn't have a closet, what about something like this?

![Capture](https://user-images.githubusercontent.com/3970626/64375171-f4ed4c80-cfea-11e9-8fa5-356e10d810e5.JPG)

**Comment by theoryshaw** [comment]
have to say these ADA bathrooms are a PITA.
How about this?...
![image](https://user-images.githubusercontent.com/507113/64376341-a7beaa00-cfed-11e9-8d00-dc9306c6ce1e.png)

**Comment by theoryshaw** [comment]
Let's do the overlap exception there, with removable cabinets doors.
![image](https://user-images.githubusercontent.com/507113/64442448-700b3d00-d095-11e9-864c-9460e5499253.png)
