### ISSUE TITLE
Type A - A471 - clear space at bathtub

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#70]
![image](https://user-images.githubusercontent.com/507113/63895636-42e3ce00-c9b5-11e9-8e86-909050400b0c.png)

**Comment by bdmock** [comment]
Should we make this bath a one vanity bath, or scrunch the two together?

![Capture](https://user-images.githubusercontent.com/3970626/64370718-a046d300-cfe4-11e9-9260-0622add09105.JPG)
![Capture](https://user-images.githubusercontent.com/3970626/64370750-b5236680-cfe4-11e9-8d11-5bf89ae27c69.JPG)

**Comment by bdmock** [comment]
For the 1BD, what do you think of this approach?

![Capture](https://user-images.githubusercontent.com/3970626/64371391-0a13ac80-cfe6-11e9-8f8c-1a2df3f2292b.JPG)

**Comment by theoryshaw** [comment]
How about this?...
![image](https://user-images.githubusercontent.com/507113/64375147-e7d05d80-cfea-11e9-9514-16e6b4eb1bb0.png)

**Comment by theoryshaw** [comment]
How about this?...
![image](https://user-images.githubusercontent.com/507113/64375381-6deca400-cfeb-11e9-9b8c-0d2ebce5ac33.png)

**Comment by theoryshaw** [comment]
Also, in general, let's not show the grab bars.  Let's just indicated there will be blocking in certain locations,  per that xx/xxx details we'll call out on the elevations.
