### ISSUE TITLE
Type A - U shaped kitchen

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#71]
![image](https://user-images.githubusercontent.com/507113/63895678-66a71400-c9b5-11e9-9058-d6f1cfc4754b.png)

**Comment by theoryshaw** [comment]
![image](https://user-images.githubusercontent.com/507113/63895697-7cb4d480-c9b5-11e9-90da-525dbf1b4288.png)

**Comment by theoryshaw** [comment]
![image](https://user-images.githubusercontent.com/507113/63895713-863e3c80-c9b5-11e9-8678-a1d559beb6a1.png)

**Comment by bdmock** [comment]
Fixing to make the 1BD ADA Type A Kitchen into an L-shape

![Capture](https://user-images.githubusercontent.com/3970626/64447524-2de7f880-d0a1-11e9-8871-5eb663656096.JPG)
![Capture](https://user-images.githubusercontent.com/3970626/64447540-3d674180-d0a1-11e9-9772-1ffd0ba5b4ca.JPG)

**Comment by bdmock** [comment]
or this?

![Capture](https://user-images.githubusercontent.com/3970626/64447737-b23a7b80-d0a1-11e9-8e22-41e7905bfc79.JPG)

**Comment by theoryshaw** [comment]
Whatta feeling?
