### ISSUE TITLE
update foundation relative to new precast beam along south wall between C and D

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#77]
![image](https://user-images.githubusercontent.com/507113/67696452-e67d3a80-f974-11e9-9bcf-bc01637ec5cb.png)

**Comment by theoryshaw** [comment]
we need Grant to size beam, first I would assume.

**Comment by lcpt** [comment]
We can make some assumptions without having precise data about the lintel, but we cannot finish without them.

**Comment by theoryshaw** [comment]
![2019-11-05 11 06 48](https://user-images.githubusercontent.com/507113/68229313-9e859580-ffbc-11e9-80e0-230cfb105efc.jpg)

@lcpt is this what we want to propose to Grant?

**Comment by lcpt** [comment]
Yes. Thanks Ryan.

**Comment by theoryshaw** [comment]
Hi Luis, i would say this one is priority to finalize. Thx.

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/68395393-ee588e00-016f-11ea-9df5-d6be2ce567d0.png)
OK, I'll design this detail and draw the sketches of the whole thing.

**Comment by theoryshaw** [comment]
Thanks Luis. 

Can you also look at this?

![image](https://user-images.githubusercontent.com/507113/68399998-e6cbc180-013c-11ea-9d7d-d2ae59a93b90.png)

**Comment by lcpt** [comment]
Yes, I'm adapting/redefining the whole thing.

**Comment by lcpt** [comment]
![page_01](https://user-images.githubusercontent.com/12873038/68614145-9a77dd00-04c0-11ea-8476-e587c26004a9.jpeg)

**Comment by lcpt** [comment]
![page_02](https://user-images.githubusercontent.com/12873038/68614180-b3808e00-04c0-11ea-82d7-3aae9b82078e.jpeg)

**Comment by lcpt** [comment]
![page_03](https://user-images.githubusercontent.com/12873038/68614222-cb581200-04c0-11ea-82a3-3cb23f32f488.jpeg)

**Comment by theoryshaw** [comment]
I think they formed and poured the footings already. 

We might have to modify this relative to that.  Maybe a greater bearing distance than 1ft?

I think they are forming and rebaring the walls right now. 

I just asked the GC for an update on where they are at.

**Comment by theoryshaw** [comment]
Yes, the footings are all poured around the perimeter of the building.

So they have a WF48 along the entirely of that south wall with the following dimensions...

![image](https://user-images.githubusercontent.com/507113/68617765-88c91200-048d-11ea-92a1-6f59378551e7.png)

The south wall, however has not been formed or rebared yet, but they are going to do that shorty.

**Comment by lcpt** [comment]
We can reinforce both faces of the wall in that zone and take advantage of the load diffusion on the wall:
![alternative](https://user-images.githubusercontent.com/12873038/68663668-6099eb80-053f-11ea-8780-2806366e18d7.jpeg)
I'll send you a sketch today.

**Comment by lcpt** [comment]
![alternative_rev01](https://user-images.githubusercontent.com/12873038/68699395-3ff38500-0583-11ea-9a35-b6318d39a38a.jpeg)

Can we do this?

**Comment by theoryshaw** [comment]
Yes, i think.  Thanks!
