### ISSUE TITLE
Clarify corner cantilever condition.

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#78]
Luis to provide OD with a clarifying sketch.

![image](https://user-images.githubusercontent.com/507113/67696737-63a8af80-f975-11e9-94d2-3ba15d678f26.png)

**Comment by lcpt** [comment]
![corner_cantilever_condition](https://user-images.githubusercontent.com/12873038/68872337-29be0400-06fe-11ea-8376-4bebbe251ee9.jpeg)
This is the solution I imagine for the cantilevers on the corners.

**Comment by lcpt** [comment]
We adopted the solution proposed by Kurt. See 'Transfer/20191203 - from SEO - sketch of cantilever conditions'
