### ISSUE TITLE
update the following details per the new change to concrete walls. 

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#79]
@lcpt to provide sketch to change the following details...

![image](https://user-images.githubusercontent.com/507113/67698446-5e009900-f978-11e9-996c-1a08003464a7.png)

![image](https://user-images.githubusercontent.com/507113/67698459-66f16a80-f978-11e9-9822-d432da0efc69.png)

**Comment by theoryshaw** [comment]
Hi @lcpt possible get these sketches by tomorrow?

**Comment by lcpt** [comment]
Yes, I'm working on it.

**Comment by lcpt** [comment]
[ramp_RC_wall_schedule.pdf](https://github.com/OpeningDesign/CTR/files/3800659/ramp_RC_wall_schedule.pdf)

Find attached the reinforcement schedule for the new RC walls for the ramp.

**Comment by lcpt** [comment]
![ramp_west_wall_hollow_core_connection_detail](https://user-images.githubusercontent.com/12873038/68074339-2e97c500-fd9a-11e9-930b-db410ddc15cf.jpeg)
This is the detail for the wall on the west side (see plan view). The detail for the East wall will be very similar.

**Comment by theoryshaw** [comment]
Hi Luis, 
Could we simplify this detail with an steel angle, if necessary?  Something like the following image (with concrete obviously).
I just think this will be easier for the concrete sub, than forming that corbel--which would be a lot of form work.

![image](https://user-images.githubusercontent.com/507113/68086329-53c71a80-fe10-11e9-9a26-cd1310251c6e.png)

---

Or maybe we could bear those 2nd floor trusses on the top of the concrete wall, so we wouldn't need this corbel (or steel angle) for load bearing.  We would only need a lateral connection at this point.

**Comment by lcpt** [comment]
![the_problem_to_solve](https://user-images.githubusercontent.com/12873038/68123192-9837e080-ff0c-11e9-8678-6319944e9796.jpeg)
I've tried to explain the reason to put those corbels in the attached file. The formwork is more complicated but I don't find a simpler solution. I'll put an alternative solution here but I think it's not simpler than this one.

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/68123552-9f132300-ff0d-11e9-85b5-c459b7fa3df7.png)

This is the solution I was talking about. The topping will be installed on a second phase so, if we want to use this detail it will need some modifications.

**Comment by theoryshaw** [comment]
Good morning. Thanks for those sketches. 

Ultimately defer to you on this.  But wanted to ask again, just to make sure.... a steel angle, like below, would not work in this condition?

![image](https://user-images.githubusercontent.com/507113/68131689-13849c80-fee3-11e9-82be-ee9928b7b8e4.png)

**Comment by lcpt** [comment]
No, it's not strong enough.

**Comment by theoryshaw** [comment]
Okay, sounds good. Thx! We'll move forward with the corbel.

**Comment by theoryshaw** [comment]
Just to ask the question.  How about using a 12" wall from the basement to 1st floor, and then an 8" wall from the 1st to the 2nd?  
Would give us a 4" ledge to bear the precast on.
Could something like that work? 

I just trying to head off GC's questions to simplify.

**Comment by theoryshaw** [comment]
Also too, sorry.  Could we get the precast guys to size these planks to support these truss loads?  So we could do without the corbel and would only need a lateral connection at these points.

**Comment by lcpt** [comment]
> Just to ask the question. How about using a 12" wall from the basement to 1st floor, and then an 8" wall from the 1st to the 2nd?
> Would give us a 4" ledge to bear the precast on.
> Could something like that work?
> 
> I just trying to head off GC's questions to simplify.

This could work.

**Comment by lcpt** [comment]
> Also too, sorry. Could we get the precast guys to size these planks to support these truss loads? So we could do without the corbel and would only need a lateral connection at these points.

The truss loads are not a problem, the structural integrity of the planks at their connections with the ramp wall (as shown in the previous sketch) is. It was Grant who asked us to take care of this problem during our last telephone, so I think there is no chance they can help us.

**Comment by theoryshaw** [comment]
> The truss loads are not a problem, the structural integrity of the planks at their connections with the ramp wall (as shown in the previous sketch) is. It was Grant who asked us to take care of this problem during our last telephone, so I think there is no chance they can help us.

Okay sounds good.  I'm going to ping Eric in here, to see if he has a preference between a 12" wall or a corbel.

Thanks, Ryan

**Comment by theoryshaw** [comment]
from gc:
![image](https://user-images.githubusercontent.com/507113/68226758-3634b500-ffb8-11e9-8228-42c9a4b7cef7.png)

@lcpt, if you could, please move forward with a 12" wall, verses using a corbel.

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/68228037-ffc95b00-fff4-11e9-921a-8d789ccc76a3.png)
OK. We'll remove the corbel and update the foundations and wall details.

**Comment by lcpt** [comment]
![ramp_rc_walls_connections_1st_floor](https://user-images.githubusercontent.com/12873038/68237990-8dfb0c80-0008-11ea-98c0-58a2c7b79c45.jpeg)

**Comment by theoryshaw** [comment]
Thanks Luis!  @chopinregis can you draft this up?  Keep the other corbel detail, however.

**Comment by chopinregis** [comment]
> Thanks Luis! @chopinregis can you draft this up? Keep the other corbel detail, however.

Here is the update
https://71-thumbnail-images.first-draft.xyz/d/20191106_CTR_Structural_Detail/
![CTR - 1st Phase - Structure - Sheet - S202 - STRUCTURAL DETAILSs](https://user-images.githubusercontent.com/13260872/68301848-d3eabb80-006e-11ea-84e7-7e7f750a51f7.jpg)

**Comment by theoryshaw** [comment]
@lcpt i took the first stab at markups.  We'll refine these and ping you later for a review.

**Comment by lcpt** [comment]
OK.
