### ISSUE TITLE
Construction joints in basement walls.

### ISSUE THREAD

**Issue by lcpt** [OpeningDesign/CTR#86]
![image](https://user-images.githubusercontent.com/12873038/68131884-15b81c80-ff1e-11e9-8095-06f775205fe7.png)

**Comment by anaiortega** [comment]
To control cracking in foundation walls, two types of joints are used:
- Vertical contraction joints (see detail 3/S200), spaced 25' at most.
- Vertical construction joints (see detail 4/S200) separating adjacent placements of concrete, that also work as contraction joints.
![joints](https://user-images.githubusercontent.com/12873329/68138737-4b163780-ff29-11e9-8c2f-5a1d0ee9c838.png)
