### ISSUE TITLE
Signage update

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#87]
from owner: 
>The official name of the community is going to be "The Current". 
> Can you design signage on the top of the building facing east towards the river with the word "Current"? The letters would be large and blue and we would need spotlights shining on the letters so that it can be seen from across the river. The lights would be on a timer to turn on in the evening and off in the morning.

**Comment by bdmock** [comment]
![CTR_logo signage update 1](https://user-images.githubusercontent.com/3970626/71280077-e7e93480-231f-11ea-8c8a-641c9c819062.JPG)
