### ISSUE TITLE
Titan screw anchors at exterior wall

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#90]
From GC:
![image](https://user-images.githubusercontent.com/507113/68226389-98d98100-ffb7-11e9-8662-947818a8169d.png)

**Comment by theoryshaw** [comment]
Eric, I assume this is what you're looking at?...
https://www.strongtie.com/mechanicalanchors_mechanicalanchoringproducts/thd_anchor/p/titen-hd

@lcpt could you let Eric know the size/spacing for using titan screws in place of anchor bolts?

**Comment by theoryshaw** [comment]
Just for clarity, i think Eric is talking about the condition below...

![image](https://user-images.githubusercontent.com/507113/68251102-0e5d4580-ffe8-11e9-88e4-6e7579ed039c.png)

**Comment by lcpt** [comment]
![selected_titen_anchor_bolt](https://user-images.githubusercontent.com/12873038/72988288-448eb200-3dec-11ea-9aeb-05459f5555c5.png)
