### ISSUE TITLE
lintels in elevator tower

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#92]
![image](https://user-images.githubusercontent.com/507113/68412015-21d7f000-0151-11ea-9007-fab1ac30a87f.png)

**Comment by anaiortega** [comment]
![hoja1](https://user-images.githubusercontent.com/12873329/68879298-778c3980-0709-11ea-898b-c47f2c32ecfd.png)
![hoja2](https://user-images.githubusercontent.com/12873329/68879303-7a872a00-0709-11ea-82e8-2d1d772f409c.png)

**Comment by theoryshaw** [comment]
Hi Ana,

Hope you had a nice Christmas/Hanukkah/Kwanzaa break! :) 

Now that we know what that precast beam will be through the elevator, I just wanted to verify what that lintel condition needs to be at the CMU wall.  See sketch below.

![image](https://user-images.githubusercontent.com/507113/71528132-1d53cc00-28a4-11ea-9c8b-a93c687d59da.png)

**Comment by anaiortega** [comment]
Thanks, Ryan, wish you all the best for the new year.
In order to design a solution for this lintel, we need to know the stage of the construction at the present time, specifically if the concrete basement wall, column and CMU elevator wall are already built.

**Comment by theoryshaw** [comment]
Hi Ana, only the footings for these areas are being formed, and poured.  They have not started on the ramp walls, or the concrete column near the elevator yet.

I would assume it will be formed how we design it.

**Comment by anaiortega** [comment]
Hi Ryan,
For the lintel on the 1st floor, we are working on this kind of solution. Can you see any constructive problem?
![sketch](https://user-images.githubusercontent.com/12873329/71734148-81016a80-2e4b-11ea-9d94-8cabdc664f20.jpg)

**Comment by theoryshaw** [comment]
Hi @anaiortega,

They don't make a CMU that size. 

Since this CMU will be exposed to the finish space, would it be possible to do something like this?

http://dev.first-draft.xyz/d/20200107_Elevator_Lintels2/

As you saw from the GC's email this is probably priority now.

Thanks!

**Comment by anaiortega** [comment]
Hi Ryan,
By no means we can reduce the column cross-section. Would it be possible to do something like this?
![pic](https://user-images.githubusercontent.com/12873329/71973828-3fd4d600-3210-11ea-8526-8bd351e6ce2f.png)

**Comment by anaiortega** [comment]
![20200108114902_001](https://user-images.githubusercontent.com/12873329/71976285-38b0c680-3216-11ea-9b19-096fb8fa17ff.jpg)
Revision of sketch sent on Nov. 14, 2019. Revision clouds in blue.

**Comment by theoryshaw** [comment]
> Hi Ryan,
> By no means we can reduce the column cross-section. Would it be possible to do something like this?
> ![pic](https://user-images.githubusercontent.com/12873329/71973828-3fd4d600-3210-11ea-8526-8bd351e6ce2f.png)

Yes, we can do something like this.  We'll draft it up.

**Comment by theoryshaw** [comment]
Hi @anaiortega, can you review the following pdf?
CTR\Transfer\20200108 - to STRUCT - review of elevator elevation\CTR - elevator elevations.pdf

Thanks, Ryan

**Comment by anaiortega** [comment]
Hi @theoryshaw,
Find attached my review
[20200109_elevator_lintels_review.pdf](https://github.com/OpeningDesign/CTR/files/4040811/20200109_elevator_lintels_review.pdf)

**Comment by anaiortega** [comment]
Hi @chopinregis,
Find review of elevator elevation:
CTR\Transfer\20200109_toARCH_review_elevator_elevation\20200109_elevator_lintels_review.pdf

**Comment by chopinregis** [comment]
thank you @anaiortega

**Comment by anaiortega** [comment]
Hi @chopinregis ,
If you don't mind, please send me the plan for review when all the corrections are made.
Tanks, Ana

**Comment by chopinregis** [comment]
> Hi @chopinregis ,
> If you don't mind, please send me the plan for review when all the corrections are made.
> Tanks, Ana

Hello @anaiortega 
You will the drawings here
CTR\Transfer\20200114 - to STRUCT - Internal Review

**Comment by anaiortega** [comment]
Thanks @chopinregis,
My review:
![rev01_1](https://user-images.githubusercontent.com/12873329/72361719-41137080-36f2-11ea-937e-6a1ce4269103.png)
![rev01_2](https://user-images.githubusercontent.com/12873329/72361735-47095180-36f2-11ea-8d29-2eafba8ef23b.png)
![rev01_2_text](https://user-images.githubusercontent.com/12873329/72361747-4b356f00-36f2-11ea-950e-3726bd3b961f.png)

**Comment by chopinregis** [comment]
hello @anaiortega , i've updated your markups, they are in the same folder as
CTR\Transfer\20200114 - to STRUCT - Internal Review

**Comment by anaiortega** [comment]
Hi  @chopinregis, 
the last detail was missing in the previous review
![1stfloor_lintel](https://user-images.githubusercontent.com/12873329/72366726-22fe3e00-36fb-11ea-8d5b-075deeb4ce36.jpg)

**Comment by anaiortega** [comment]
> hello @anaiortega , i've updated your markups, they are in the same folder as
> CTR\Transfer\20200114 - to STRUCT - Internal Review

It's fine by me

**Comment by chopinregis** [comment]
alright @anaiortega the 1st floor Lintel detail 4/S400 has been updated at same location
CTR\Transfer\20200114 - to STRUCT - Internal Review

**Comment by anaiortega** [comment]
Hi @chopinregis . The checking of the 1st floor Lintel detail:
![202001150834_1st_floor_elevator_lintel](https://user-images.githubusercontent.com/12873329/72418572-639d9c00-377b-11ea-923b-112af6a862a4.jpg)

**Comment by theoryshaw** [comment]
A 4" radius would touch the inside edges of the CMU block. Is that OK? Would 3" radius work?

---

  We fixed the cadding note on the latest drawing.

**Comment by anaiortega** [comment]
It's 2" radius

**Comment by theoryshaw** [comment]
Sorry, meant 4" diameter, would touch the outside edge of cmu..  That okay?

**Comment by anaiortega** [comment]
Then 1 1/2" radius, 3" diameter will ok ;-)

**Comment by theoryshaw** [comment]
Hi @anaiortega ,

![image](https://user-images.githubusercontent.com/507113/72452220-cd6d7400-3782-11ea-826b-e60f41f2f0cb.png)

---

![image](https://user-images.githubusercontent.com/507113/72455187-f5130b00-3787-11ea-907b-59f08fbabd2e.png)

**Comment by anaiortega** [comment]
Hi @theoryshaw,
For the second one (9 ft), no problem.
For the first one (opening 60.5"), I think it will be ok, since the load is low. Nevertheless, I'll verify it tomorrow morning.

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
For the opening for louver, ok as well

**Comment by anaiortega** [comment]
Hi @theoryshaw ,
![20200116093140_001](https://user-images.githubusercontent.com/12873329/72515103-9fa23100-384f-11ea-9e8f-c532d80c280e.jpg)

If finally, the current design of the elevator shaft is viable for the elevator installation, we should add a couple of ties between the column and the 6" CMU wall to ensure the stability of the latter.

**Comment by anaiortega** [comment]
On the other hand, I would like to add a bond beam under the opening for louver
![screenshot_1](https://user-images.githubusercontent.com/12873329/72516163-8306f880-3851-11ea-9aa7-93e6384c154f.png)
