### ISSUE TITLE
Detail of built up curb and floor

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#94]
Need a detail of the condition below.

This is the GC's sketch. 

@lcpt, Defer to you on best approach.

![image](https://user-images.githubusercontent.com/507113/68412605-251fab80-0152-11ea-9d22-9830fc02f62a.png)

**Comment by lcpt** [comment]
This is the reinforcement I propose for this element:
![built_up_curb_reinforcement](https://user-images.githubusercontent.com/12873038/68666525-60501f00-0544-11ea-94d2-22fae2481548.png)

Concerning the structural filling at left, any lightweight structural filling will do. We can put a 6" EPS layer and the 3" topping over it.

**Comment by theoryshaw** [comment]
@lcpt what psi EPS insulation would you recommend under the topping?

![image](https://user-images.githubusercontent.com/507113/69355908-3b486400-0c48-11ea-8cf0-3695fef311c6.png)

**Comment by theoryshaw** [comment]
![image](https://user-images.githubusercontent.com/507113/69396993-e63d3a00-0ca9-11ea-9136-5ff7b5196717.png)

Also, what's the O.C. spacing of that?

**Comment by lcpt** [comment]
Sorry it was #4 1'-0" o/c. I've not calculated its length but an embedment of 8 inches (ca. 20 cm) will be enough.

**Comment by lcpt** [comment]
> @lcpt what psi EPS insulation would you recommend under the topping?
> 
> ![image](https://user-images.githubusercontent.com/507113/69355908-3b486400-0c48-11ea-8cf0-3695fef311c6.png)
![sub_slab_eps_fill](https://user-images.githubusercontent.com/12873038/69501640-3238ea80-0f07-11ea-8d19-58818359ef7f.png)
40 psi will do.

**Comment by theoryshaw** [comment]
Can 25psi work?

**Comment by lcpt** [comment]
Not really. The elastic modulus of the EPS drops with its compressive strength, and we a have a relatively thick (6 inches (ca. 15 cm)) EPS layer. If we put a softer material we risk having some cracks in the topping.

**Comment by lcpt** [comment]
![image](https://user-images.githubusercontent.com/12873038/69544534-378e4780-0f90-11ea-8f1c-3e29b7e3ceac.png)
