### ISSUE TITLE
Please provide exact locations for all holddowns attaching to the precast.  

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#95]
From Precast supplier...

> Please provide exact locations for all holddowns attaching to the precast.  Some of the loads are large and require extra reinforcing.  We need exact location to design the precast.

**Comment by lcpt** [comment]
Key plan:
![key_plan](https://user-images.githubusercontent.com/12873038/70076516-3e0b6780-15ff-11ea-8c9c-97f166278025.jpeg)

Hold-down anchor types:
![holddown_anchors_position](https://user-images.githubusercontent.com/12873038/70076611-6f843300-15ff-11ea-9401-88776a61921a.jpeg)

Sketches:
![sketches](https://user-images.githubusercontent.com/12873038/70076657-875bb700-15ff-11ea-81b0-062185baab86.jpeg)

I think you can put the locations of the holddowns in a drawing with this information. If something is not clear, please let me know.

**Comment by theoryshaw** [comment]
@lcpt Can you push the actual spreadsheet files for the shear wall schedule and the hold down schedule and other schedules? I think there might be a quick way where i can translate that, via a CSV, into Revit.

**Comment by lcpt** [comment]
There it goes: _CLOSED_Cannery District - Eau Claire/Transfer/20191203 -f from STRUCT - hold-downs anchors location/holddown_anchors_position.ods
