### ISSUE TITLE
Please provide a detail for how holddowns will connect to the plank. 

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#96]
From Precast supplier

> Please provide a detail for how holddowns will connect to the plank.  Attached is a detail we have used on similar projects. 

![image](https://user-images.githubusercontent.com/507113/69580897-1aab4180-0f9b-11ea-97bf-bb51d8de86a3.png)

**Comment by lcpt** [comment]
![hold_down_detail_with_diameters](https://user-images.githubusercontent.com/12873038/70053224-3d5ddb80-15d5-11ea-9030-28dc0e185c20.jpeg)

**Comment by theoryshaw** [comment]
Thanks Luis,

Are you suggesting the contractor can choose from the following 3 hold down options?

- Simpson hdu4
- Simpson hd19
- Simpson hdu4-sds2.5

Thanks, Ryan

**Comment by theoryshaw** [comment]
Nevermind, i see they are referenced back to the shear wall schedule. 
Thanks.

**Comment by lcpt** [comment]
Correct.
