### ISSUE TITLE
Concrete or CMU pier near elevator

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#98]
from precast supplier:

> To answer the questions about using a precast column at Grids B,1 we recommend using a CMU or CIP pier.  Precast would be difficult to install due to walls nearby being so close.

**Comment by anaiortega** [comment]
![column_B1](https://user-images.githubusercontent.com/12873329/69974954-902c8a00-1526-11ea-83ec-c3547ea4f3c6.png)

**Comment by theoryshaw** [comment]
Thanks Ana, Is it possible to go with a CMU column here instead?  I think it will be easier for the GC to integrate a CMU column into the CMU walls of the elevator shaft.

**Comment by anaiortega** [comment]
The column bears a compressive force of about 1200 kN. If we design it in CMU, the cross-section would probably be 24x40"

**Comment by theoryshaw** [comment]
Thanks Ana, we'll keep the concrete column as you designed.

**Comment by theoryshaw** [comment]
Good morning @anaiortega 
Can you review this? Circled in red.
http://dev.first-draft.xyz/d/20191211_CTR_column_at_elevator/

Would like to issue this today to the GC.

**Comment by lcpt** [comment]
Good morning.

Ana is attending a course today. I've compared the drawing with hers manuscript. You can find my remarks in first-draft.
