### ISSUE TITLE
Lintel condition at east intake.

### ISSUE THREAD

**Issue by theoryshaw** [OpeningDesign/CTR#99]
October 8th sketch from @anaiortega 

![image](https://user-images.githubusercontent.com/507113/69583271-1fbebf80-0fa0-11ea-979d-0368e97b95c7.png)

Photo a couple days ago...

![intake louver](https://user-images.githubusercontent.com/507113/69583348-5268b800-0fa0-11ea-9b2a-b9b89d674ac2.jpeg)

Proposed sketch..

![image](https://user-images.githubusercontent.com/507113/69583422-7af0b200-0fa0-11ea-8295-5b21376b5c9c.png)

Existing condition...

![overview 11-25 (1)](https://user-images.githubusercontent.com/507113/69583656-feaa9e80-0fa0-11ea-8ae1-9039baaed838.jpg)

**Comment by lcpt** [comment]
Sorry, it's my fault. Ana has explained to me that you have made a change for this lintel and yesterday I've picked the old version sketch. The good one is the sketch sent by Ana you have put in first place.

**Comment by lcpt** [comment]
On the other hand, in the photo the three rebars at bottom seem too tight together, maybe it's only the perspective.
